name: Enderbutt
version: ${project.version}
main: me.ftsos.enderbutt.enderbutt.Enderbutt
authors: [ ftsos ]
description: EnderButt :D
commands:
  enderbutt:
    description: gives you an ender butt
  enderbuttreload:
    description: reloads config of the enderbutt plugin